# Exercises from the Machine Learning Foundations Youtube Course by Jon Krohn

## Exercises on Tensor Operations — Topic 15 of Machine Learning Foundations

In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
import torch

In [16]:
import tensorflow as tf

2023-01-22 06:58:19.278461: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


### What is Y Transpose?

In [13]:
# Using numpy 
Y = np.array([[42, 4, 7,99],[-99,-3,17,22]])
Y

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [9]:
# Y transpose
Y.T

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

In [14]:
# Using pytorch
Y_T = torch.tensor([[42, 4, 7,99],[-99,-3,17,22]])
Y_T

tensor([[ 42,   4,   7,  99],
        [-99,  -3,  17,  22]])

In [12]:
# Y_T transpose
Y_T.T

tensor([[ 42, -99],
        [  4,  -3],
        [  7,  17],
        [ 99,  22]])

In [17]:
# Using tensorflow
Y_TF = tf.Variable([[42, 4, 7,99],[-99,-3,17,22]])
Y_TF

2023-01-22 06:58:23.978137: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]], dtype=int32)>

In [18]:
# Y_TF transpose
tf.transpose(Y_TF)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]], dtype=int32)>

### What is the Hadamard product of the following matrics

In [21]:
I = np.array([[25, 10],[-2,-1]])
I

array([[25, 10],
       [-2, -1]])

In [23]:
J = np.array([[-1, 7],[10,8]])
J

array([[-1,  7],
       [10,  8]])

The Hadamard product:  $I \odot J$ is ...

In [25]:
# Hadamard product of I and J
I * J

array([[-25,  70],
       [-20,  -8]])

### What is the dot product of the vectors w and x

In [33]:
w = np.array([-1,2,-2])
x = np.array([5,10,0])

In [34]:
# the dot product of w and x is: 
np.dot(w,x)

15